apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-green
  labels:
    app: nodejs-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
      version: green
  template:
    metadata:
      labels:
        app: nodejs-app
        version: green
    spec:
      containers:
      - name: nodejs-app
        image: devops-cloud-project:latest
        imagePullPolicy: Never   # local Minikube image
        env:
        - name: APP_VERSION
          value: "v2"
        - name: APP_COLOR
          value: "green"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
